pipeline {
    agent any

    stages {
        stage("Limpando a workspace") {
           steps {
                    slackSend(color: 'info', message: "Iniciando processo de continuos deployment do projeto: ${JOB_URL}", channel: 'devops-rafael')
                    sh 'pwd'
                    deleteDir()
           }
       }

       stage("Clonando projeto do github") {
           steps {
               git credentialsId: 'github-ssh', url: "git@github.com:sunwebdeveloper/infraagil.git"
           }
       }

       stage('Rodar testes unitarios') {
           steps {
               sh "mvn clean test "
           }
       }

       stage('Gerando artefato') {
           steps {
               sh "mvn clean package -DskipTests "
           }
       }

       stage('Deploy') {
           steps {
               sh 'scp -o StrictHostKeyChecking=no -i /home/vagrant/jenkins target/alura-forum.war vagrant@192.168.33.20:/home/vagrant/alura-forum.war'
               sh "ssh -o StrictHostKeyChecking=no -i /home/vagrant/jenkins vagrant@192.168.33.20 'sudo mv /home/vagrant/alura-forum.war /var/lib/tomcat8/webapps/alura-forum.war'"
               slackSend(color: 'info', message: "Continuos deployment do projeto: ${JOB_URL} realizado com sucesso.", channel: 'devops-rafael')
           }
       }
    }
}
