# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  
  config.vm.define :db do |db_config|
    config.vm.network "private_network", ip: "192.168.33.10"
    db_config.vm.hostname = "database"
    db_config.vm.provider :virtualbox do |vb|
      vb.name = "database"
    end
    db_config.vm.provision :ansible do |ansible|
        ansible.playbook = "ansible/database.yml"
    end
  end

  config.vm.define :web do |web_config|
      config.vm.network "private_network", ip: "192.168.33.20"
      web_config.vm.hostname = "web"
      web_config.vm.provider :virtualbox do |vb|
        vb.name = "web"
      end
      web_config.vm.provision :ansible do |ansible|
          ansible.playbook = "ansible/web.yml"
      end
  end

  config.vm.define :ci do |ci_config|
      config.vm.network "private_network", ip: "192.168.33.30"
      ci_config.vm.hostname = "ci"
      ci_config.vm.provider :virtualbox do |vb|
        vb.name = "ci"
      end
      ci_config.vm.provision :ansible do |ansible|
          ansible.playbook = "ansible/ci.yml"
      end
  end
end